# Workflowの名前
name: EC2 auto deploy

# masterにpushされた時にデプロイする
on:
 push:
   branches:
     - master
 workflow_dispatch:

#実行される処理
jobs:
 build:
   # 実行環境の指定
   runs-on: macos-latest
   steps:

     # デプロイする
     - name: Deploy
       run: |
         # SSH接続して、git pullする
         echo "${{ secrets.PRIVATE_KEY }}" > private_key
         chmod 600 private_key
         ssh -oStrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} -i private_key "cd /var/www/portfolio && git fetch origin && git pull --rebase origin master && npm run build"


